[build]
builder = "NIXPACKS"

[[services]]
name = "api"
rootDirectory = "apps/api"
[services.api.variables]
PORT = "3001"
REDIS_URL = "${{Redis.REDIS_URL}}"
DATABASE_URL = "${{Postgres.DATABASE_URL}}"

[[services]]
name = "web"
rootDirectory = "apps/web"
[services.web.variables]
NEXT_PUBLIC_API_URL = "https://${{api.RAILWAY_PUBLIC_DOMAIN}}"
